version: '3'

networks:
  whaticket:

services:

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile

    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASS=${MYSQL_ROOT_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE:-whaticket}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - BACKEND_URL=${BACKEND_URL}
      - FRONTEND_URL=${FRONTEND_URL}
      - PROXY_PORT=${PROXY_PORT:-443}
      - CHROME_ARGS=--no-sandbox --disable-setuid-sandbox

    expose:
      - "3000"

    volumes:
      - whaticket_public:/usr/src/app/public/
      - whaticket_auth:/usr/src/app/.wwebjs_auth/

    depends_on:
      mysql:
        condition: service_healthy

    restart: unless-stopped

    networks:
      - whaticket


  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile

    environment:
      - URL_BACKEND=backend:3000
      - REACT_APP_BACKEND_URL=${BACKEND_URL}:${PROXY_PORT:-443}/
      - FRONTEND_SERVER_NAME=${FRONTEND_SERVER_NAME}
      - BACKEND_SERVER_NAME=${BACKEND_SERVER_NAME}

    expose:
      - "80"

    depends_on:
      - backend

    restart: unless-stopped

    networks:
      - whaticket


  mysql:
    image: ${MYSQL_ENGINE:-mariadb}:${MYSQL_VERSION:-10.6}

    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin

    volumes:
      - whaticket_mysql:/var/lib/mysql

    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-whaticket}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TZ:-America/Sao_Paulo}

    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

    networks:
      - whaticket


volumes:
  whaticket_mysql:
  whaticket_public:
  whaticket_auth:
